<a href="https://colab.research.google.com/github/SamanvithaBolem/SamanvithaBolem/blob/main/breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

data = pd.read_csv('/content/cancerdata.csv')

In [39]:
data.head()

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                 0.101594
1    842517         M  ...          0.2750                 0.079397
2  84300903         M  ...          0.3613                 0.088802
3  84348301         M  ...          0.6638                 0.086210
4  84358402         M  ...          0.2364                 0.087483

[5 rows x 32 columns]

In [40]:
data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [41]:
data = data.drop(columns=['id'])

In [42]:
data.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M    14.204716  ...          0.4601                 0.101594
1         M    18.483496  ...          0.2750                 0.079397
2         M    15.516300  ...          0.3613                 0.088802
3         M    15.540583  ...          0.6638                 0.086210
4         M    14.005198  ...          0.2364                 0.087483

[5 rows x 31 columns]

In [43]:
data.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_wors',
       'concavity_worst', 'concave points_worst', 'symmetry_worst',
       'fractal_dimension_worst'],
      dtype='object')

In [45]:
X = data.loc[:,['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_wors',
       'concavity_worst', 'concave points_worst', 'symmetry_worst',
       'fractal_dimension_worst']]
      
Y = data.loc[:,'diagnosis']      

In [46]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size=0.2)

In [47]:
Xtrain.shape

(455, 30)

In [48]:
Xtest.shape

(114, 30)

In [49]:
Ytrain.shape

(455,)

In [50]:
Ytest.shape

(114,)

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
model = LogisticRegression()

In [53]:
model.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [54]:
model.score(Xtrain,Ytrain)

0.945054945054945

In [55]:
model.coef_

array([[-2.95847027e-02, -6.65525999e-02, -7.45830821e-01,
         2.91601260e-02, -6.68311338e-03,  9.98283008e-04,
        -1.24427066e-03,  6.92274524e-03, -7.40174985e-03,
        -6.39475785e-03, -1.44824304e-02, -7.81148357e-02,
         1.82146341e-02,  6.68180461e-02, -5.44513331e-04,
        -2.14080452e-03,  1.82603575e-02,  4.28311405e-03,
        -2.60583143e-03, -1.00699895e-03, -4.49698905e-01,
         2.27456669e-01,  4.33818434e-01,  6.37308587e-03,
         1.54484876e-02, -4.12354662e-02,  2.16347409e-01,
        -2.52493303e-02,  3.79814561e-02, -6.32632893e-03]])

In [56]:
model.intercept_

array([-0.06988378])

In [57]:
Ypred = model.predict(Xtest)

In [58]:
Ypred

array(['M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B'], dtype=object)

In [59]:
Ytest

262    M
66     B
420    B
243    B
325    B
      ..
432    M
119    M
525    B
3      M
452    B
Name: diagnosis, Length: 114, dtype: object

In [60]:
from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score

In [61]:
print(accuracy_score(Ytest, Ypred))

0.9210526315789473


In [62]:
print(confusion_matrix(Ytest, Ypred))

[[65  7]
 [ 2 40]]


In [63]:
print(classification_report(Ytest,Ypred))

              precision    recall  f1-score   support

           B       0.97      0.90      0.94        72
           M       0.85      0.95      0.90        42

    accuracy                           0.92       114
   macro avg       0.91      0.93      0.92       114
weighted avg       0.93      0.92      0.92       114

