<a href="https://colab.research.google.com/github/SamanvithaBolem/SamanvithaBolem/blob/main/Iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = sns.load_dataset('iris')

In [12]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
print(data.shape)
print(data.info())

(150, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [7]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
X = data.loc[:,['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

y = data.loc[:,'species']

In [11]:
X = data.iloc[:,:-1]  #same as above
y= data.iloc[:,-1]

In [25]:
#split out validation dataset
from sklearn.model_selection import train_test_split

Xtrain,Xtest, ytrain, ytest = train_test_split(X,y, test_size=0.2)

In [15]:
Xtrain.shape

(120, 4)

In [16]:
Xtest.shape

(30, 4)

In [17]:
ytrain.shape

(120,)

In [18]:
ytest.shape

(30,)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression()

In [29]:
model.fit(Xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
model.score(Xtrain,ytrain)

0.975

In [31]:
model.coef_

array([[-0.38858806,  0.91473001, -2.35593746, -1.01431433],
       [ 0.56558576, -0.40442773, -0.17234911, -0.96395642],
       [-0.1769977 , -0.51030228,  2.52828657,  1.97827075]])

In [32]:
model.intercept_

array([  9.1248221 ,   2.05797561, -11.1827977 ])

In [33]:
ypred = model.predict(Xtest)

In [34]:
ypred

array(['setosa', 'virginica', 'virginica', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'virginica',
       'setosa', 'virginica', 'virginica', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'virginica', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica'], dtype=object)

In [36]:
ytest

9          setosa
103     virginica
129     virginica
79     versicolor
43         setosa
49         setosa
149     virginica
96     versicolor
36         setosa
108     virginica
29         setosa
104     virginica
124     virginica
115     virginica
50     versicolor
70     versicolor
57     versicolor
41         setosa
24         setosa
131     virginica
42         setosa
123     virginica
12         setosa
132     virginica
8          setosa
22         setosa
102     virginica
40         setosa
17         setosa
128     virginica
Name: species, dtype: object

In [37]:
from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score

In [39]:
print(accuracy_score(ytest, ypred))

0.9666666666666667


In [40]:
print(confusion_matrix(ytest, ypred))

[[13  0  0]
 [ 0  4  1]
 [ 0  0 12]]


In [42]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       1.00      0.80      0.89         5
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30

