<a href="https://colab.research.google.com/github/SamanvithaBolem/SamanvithaBolem/blob/main/Knearest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import seaborn as sns

In [118]:
data = sns.load_dataset('iris')

In [119]:
print('Data Shape',data.shape)
print('Data Info', data.info())
print('Data Head', data.head())
print(data.columns)

Data Shape (150, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
Data Info None
Data Head    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [120]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [121]:
X = data.loc[:,['sepal_length','sepal_width', 'petal_length', 'petal_width']]

Y = data.loc[:,'species']

In [122]:
X.shape

(150, 4)

In [123]:
Y.shape

(150,)

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,
                                                Y,
                                                train_size=0.90,
                                                test_size=0.10)

In [126]:
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)
print(Ytest.shape)

(135, 4)
(15, 4)
(135,)
(15,)


In [127]:
from sklearn.neighbors import KNeighborsClassifier


In [128]:
model = KNeighborsClassifier(n_neighbors=5)

In [129]:
model.fit(Xtrain,Ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [130]:
Ypred = model.predict(Xtest)

In [131]:
Ypred

array(['versicolor', 'virginica', 'virginica', 'virginica', 'setosa',
       'setosa', 'setosa', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'virginica'],
      dtype=object)

In [132]:
Ytest

99     versicolor
128     virginica
146     virginica
127     virginica
14         setosa
17         setosa
23         setosa
79     versicolor
35         setosa
77     versicolor
96     versicolor
40         setosa
57     versicolor
67     versicolor
114     virginica
Name: species, dtype: object

In [133]:
from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score

In [134]:
print(sklearn.metrics.accuracy_score(Ytest,Ypred))

1.0


In [135]:
print(sklearn.metrics.confusion_matrix(Ytest,Ypred))

[[5 0 0]
 [0 6 0]
 [0 0 4]]


In [136]:
print(sklearn.metrics.classification_report(Ytest,Ypred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         5
  versicolor       1.00      1.00      1.00         6
   virginica       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



1. 70/30 96% acc 
2. 80/20 96.7% acc
3. 85/15 91.4% acc
4. 90/10 100%acc
