<a href="https://colab.research.google.com/github/SamanvithaBolem/SamanvithaBolem/blob/main/matrixintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

data = pd.read_csv('/content/BankCreditCard.csv')

In [3]:
data.head()

Customer ID  Credit_Amount  ...  Previous_Payment_June  Default_Payment
0            1        20000.0  ...                    0.0                1
1            2       220000.0  ...                 2000.0                1
2            3        90000.0  ...                 5000.0                0
3            4        50000.0  ...                 1000.0                0
4            5        50000.0  ...                  679.0                0

[5 rows x 25 columns]

In [11]:
data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Credit_Amount           30000 non-null  float64
 1   Gender                  30000 non-null  int64  
 2   Academic_Qualification  30000 non-null  int64  
 3   Marital                 30000 non-null  int64  
 4   Age_Years               30000 non-null  int64  
 5   Repayment_Status_Jan    30000 non-null  int64  
 6   Repayment_Status_Feb    30000 non-null  int64  
 7   Repayment_Status_March  30000 non-null  int64  
 8   Repayment_Status_April  30000 non-null  int64  
 9   Repayment_Status_May    30000 non-null  int64  
 10  Repayment_Status_June   30000 non-null  int64  
 11  Jan_Bill_Amount         30000 non-null  float64
 12  Feb_Bill_Amount         30000 non-null  float64
 13  March_Bill_Amount       30000 non-null  float64
 14  April_Bill_Amount       30000 non-null

In [6]:
data = data.drop(columns=['Customer ID'])

In [7]:
data.head()

Credit_Amount  Gender  ...  Previous_Payment_June  Default_Payment
0        20000.0       2  ...                    0.0                1
1       220000.0       2  ...                 2000.0                1
2        90000.0       2  ...                 5000.0                0
3        50000.0       2  ...                 1000.0                0
4        50000.0       1  ...                  679.0                0

[5 rows x 24 columns]

In [12]:
data.columns

Index(['Credit_Amount', 'Gender', 'Academic_Qualification', 'Marital',
       'Age_Years', 'Repayment_Status_Jan', 'Repayment_Status_Feb',
       'Repayment_Status_March', 'Repayment_Status_April',
       'Repayment_Status_May', 'Repayment_Status_June', 'Jan_Bill_Amount',
       'Feb_Bill_Amount', 'March_Bill_Amount', 'April_Bill_Amount',
       'May_Bill_Amount', 'June_Bill_Amount', 'Previous_Payment_Jan',
       'Previous_Payment_Feb', 'Previous_Payment_March',
       'Previous_Payment_April', 'Previous_Payment_May',
       'Previous_Payment_June', 'Default_Payment'],
      dtype='object')

In [16]:
X = data.loc[:,['Credit_Amount', 'Gender', 'Academic_Qualification', 'Marital',
             'Age_Years', 'Repayment_Status_Jan', 'Repayment_Status_Feb',
             'Repayment_Status_March', 'Repayment_Status_April',
             'Repayment_Status_May', 'Repayment_Status_June', 'Jan_Bill_Amount',
             'Feb_Bill_Amount', 'March_Bill_Amount', 'April_Bill_Amount',
             'May_Bill_Amount', 'June_Bill_Amount', 'Previous_Payment_Jan',
             'Previous_Payment_Feb', 'Previous_Payment_March',
             'Previous_Payment_April', 'Previous_Payment_May']]
      
Y = data.loc[:,'Default_Payment']      

In [18]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size=0.2)

In [19]:
Xtrain.shape

(24000, 22)

In [20]:
Xtest.shape

(6000, 22)

In [21]:
Ytrain.shape

(24000,)

In [22]:
Ytest.shape

(6000,)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()

In [26]:
model.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
model.score(Xtrain,Ytrain)

0.77975

In [28]:
model.coef_

array([[-4.98011565e-06, -3.81934094e-05, -4.80909491e-05,
        -4.03620089e-05, -6.84109554e-04,  4.49260142e-05,
         3.42276385e-05,  2.83678809e-05,  2.57363374e-05,
         2.41746054e-05,  2.20799893e-05, -2.33037320e-06,
         8.42967505e-07,  3.29015802e-06, -6.21966449e-07,
         2.35047401e-06,  2.01068891e-06, -3.72014624e-05,
        -1.79017328e-05, -8.43095869e-06, -8.96739542e-06,
        -1.07282421e-05]])

In [29]:
model.intercept_

array([-2.21127012e-05])

In [30]:
Ypred = model.predict(Xtest)

In [31]:
Ypred

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
Ytest

10616    0
2787     1
20114    0
20510    0
21163    0
        ..
23408    0
28847    0
22429    0
10674    0
12665    0
Name: Default_Payment, Length: 6000, dtype: int64

In [33]:
from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score

In [35]:
print(accuracy_score(Ytest, Ypred))

0.7755


In [36]:
print(confusion_matrix(Ytest, Ypred))

[[4650    2]
 [1345    3]]


In [37]:
print(classification_report(Ytest,Ypred))

              precision    recall  f1-score   support

           0       0.78      1.00      0.87      4652
           1       0.60      0.00      0.00      1348

    accuracy                           0.78      6000
   macro avg       0.69      0.50      0.44      6000
weighted avg       0.74      0.78      0.68      6000

